name: Build Android APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: true
      - run: flutter --version
      - run: cd myapp && flutter pub get
      - run: cd myapp && flutter build apk --release --no-tree-shake-icons
      - uses: actions/upload-artifact@v4
        with:
          name: Zion-Hymns-Release
          path: myapp/build/app/outputs/flutter-apk/app-release.apk